name = "cloudmail-ph-japanjp"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[triggers]
crons = ["0 16 * * *"]

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
